# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for SSD-TestKit
# Auto-generated by build.py

import os, sys
import playwright as _pw
_playwright_driver = os.path.join(os.path.dirname(_pw.__file__), 'driver')

block_cipher = None

a = Analysis(
    ['run_test.py'],
    pathex=['..'],  # Ensure ssd-testkit root is found before PYTHONPATH entries
    binaries=[],
    datas=[
    ('../tests/__init__.py', 'tests'),
    ('../tests/integration/__init__.py', 'tests/integration'),
    ('../tests/integration/Config', 'tests/integration/Config'),
    ('../tests/integration/lib', 'tests/integration/lib'),
    ('../framework', 'framework'),
    ('../lib', 'lib'),
    ('../pytest.ini', '.'),
    ('build_config.yaml', '.'),
    # playwright driver (node.exe + package/cli.js) — required at runtime.
    # The playwright Python package locates node.exe relative to its own
    # __file__, so the driver must land at playwright/driver/ inside the
    # extracted bundle (sys._MEIPASS/playwright/driver/).
    (_playwright_driver, 'playwright/driver'),
    ],
    hiddenimports=[
        # stdlib modules not always auto-detected by PyInstaller 6.x
        'configparser',
        'linecache',
        'tokenize',
        'token',
        'dis',
        'opcode',
        # third-party dependencies
        'pytest',
        'pytest_order',
        'pytest_asyncio',
        'pywinauto',
        'pyautogui',
        'PIL',
        'jsonschema',
        'psutil',
        'wmi',
        'async_timeout',
        # playwright (PHM web UI automation)
        # Python package + all _impl submodules (not auto-detected by PyInstaller)
        'playwright',
        'playwright.sync_api',
        'playwright.async_api',
        'playwright._impl._api_types',
        'playwright._impl._browser',
        'playwright._impl._browser_context',
        'playwright._impl._browser_type',
        'playwright._impl._connection',
        'playwright._impl._driver',
        'playwright._impl._errors',
        'playwright._impl._helper',
        'playwright._impl._local_utils',
        'playwright._impl._network',
        'playwright._impl._page',
        'playwright._impl._playwright',
        'playwright._impl._sync_base',
        'greenlet',
        'pyee',
        'pyee.base',
        # pywin32 - C extension DLLs not auto-detected by PyInstaller
        'win32api',
        'win32con',
        'win32gui',
        'win32process',
        'win32security',
        'win32service',
        'win32event',
        'win32file',
        'win32pipe',
        'win32print',
        'win32clipboard',
        'win32ts',
        'winerror',
        'pywintypes',
        'pythoncom',
        'win32com',
        'win32com.client',
        'win32com.server',
        'win32com.shell',
        'win32com.shell.shell',
        'win32com.shell.shellcon'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['run_test_hook.py'],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='RunTest',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
