# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for SSD-TestKit
# Auto-generated by build.py

block_cipher = None

a = Analysis(
    ['run_test.py'],
    pathex=['..'],  # Ensure ssd-testkit root is found before PYTHONPATH entries
    binaries=[],
    datas=[
    ('../tests/__init__.py', 'tests'),
    ('../tests/integration/__init__.py', 'tests/integration'),
    ('../tests/integration/Config', 'tests/integration/Config'),
    ('../tests/integration/lib', 'tests/integration/lib'),
    ('../framework', 'framework'),
    ('../lib', 'lib'),
    ('../pytest.ini', '.'),
    ('build_config.yaml', '.'),
    ],
    hiddenimports=[
        # stdlib modules not always auto-detected by PyInstaller 6.x
        'linecache',
        'tokenize',
        'token',
        'dis',
        'opcode',
        # third-party dependencies
        'pytest',
        'pytest_order',
        'pytest_asyncio',
        'pywinauto',
        'pyautogui',
        'PIL',
        'jsonschema',
        'psutil',
        'wmi',
        'async_timeout',
        # pywin32 - C extension DLLs not auto-detected by PyInstaller
        'win32api',
        'win32con',
        'win32gui',
        'win32process',
        'win32security',
        'win32service',
        'win32event',
        'win32file',
        'win32pipe',
        'win32print',
        'win32clipboard',
        'win32ts',
        'winerror',
        'pywintypes',
        'pythoncom',
        'win32com',
        'win32com.client',
        'win32com.server',
        'win32com.shell',
        'win32com.shell.shell',
        'win32com.shell.shellcon'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['run_test_hook.py'],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='RunTest',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
