"""
PHM (Powerhouse Mountain) UI Monitor

Web UI automation for PHM using Playwright.

PHM is a Node.js application that serves a web interface on
``http://localhost:<port>`` (default 1337).  This module drives the
browser-based UI via Playwright instead of a native Win32 automation tool.

Architecture (confirmed 2026-03-02):
    PowerhouseMountain.exe  â†’  Node.js backend (localhost:1337)
                            â†’  Browser opens http://localhost:1337

.. note::
    CSS selectors / locators below marked ``# TODO`` must be verified
    after launching PHM and inspecting elements with browser DevTools or
    ``playwright codegen http://localhost:1337``.

Usage::

    from lib.testtool.phm.ui_monitor import PHMUIMonitor

    monitor = PHMUIMonitor(host='localhost', port=1337)
    monitor.wait_for_ready(timeout=30)
    monitor.open_browser(headless=False)
    monitor.navigate_to_collector()
    monitor.set_cycle_count(10)
    monitor.set_test_duration(60)
    monitor.set_modern_standby_mode(True)
    monitor.start_test()
    monitor.wait_for_completion(timeout=3600)
    monitor.take_screenshot('./testlog/result.png')
    monitor.close_browser()
"""

import time
import os
import socket
from typing import Optional
from pathlib import Path

try:
    from playwright.sync_api import sync_playwright, Page, Browser, BrowserContext
    from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
    _PLAYWRIGHT_AVAILABLE = True
except ImportError:
    sync_playwright = None
    Page = None
    Browser = None
    BrowserContext = None
    PlaywrightTimeoutError = Exception
    _PLAYWRIGHT_AVAILABLE = False

from .exceptions import PHMUIError, PHMTimeoutError
from lib.logger import get_module_logger

logger = get_module_logger(__name__)

# ---------------------------------------------------------------------------
# CSS Selectors / Locators â€” UPDATE after inspecting real PHM Web UI
# ---------------------------------------------------------------------------
# Use browser DevTools (F12) or:
#   playwright codegen http://localhost:1337
# to find the real selectors.

_SEL_COLLECTOR_TAB    = 'a[href*="collector"], button:has-text("Collector")'  # TODO
_SEL_START_BTN        = 'button:has-text("Start")'                            # TODO
_SEL_STOP_BTN         = 'button:has-text("Stop")'                             # TODO
_SEL_STATUS_LABEL     = '[data-testid="status"], .status-label'               # TODO
# Legacy / unused placeholders kept for reference only — use _sel_counter_field() instead
_SEL_CYCLE_INPUT      = ''   # replaced by _sel_counter_field()
_SEL_DURATION_INPUT   = ''   # replaced by _sel_counter_field()
_SEL_MODERN_STANDBY   = ''   # replaced by _sel_preset_scenario_radio()

# ---------------------------------------------------------------------------
# Collector tab — additional selectors (verify with playwright codegen)
# ---------------------------------------------------------------------------
# Collection Options accordion toggle
# NOTE: do NOT mix Playwright text= engine with CSS selectors via comma —
# the whole string would be parsed as CSS and fail.  Keep these as pure CSS.
_SEL_COLLECTION_OPTIONS_TOGGLE = (
    'button:has-text("Collection Options"), '
    '[data-testid="collection-options-toggle"]'     # TODO: verify with DevTools
)

# Delayed / Duration selectors are now generated by _sel_counter_field(); see below.
# These constants remain as empty strings so existing code that references them
# still compiles, but the real selectors are built dynamically.
_SEL_DELAYED_START    = ''   # replaced by _sel_counter_field()
_SEL_SCENARIO_DURATION = ''  # replaced by _sel_counter_field()


def _sel_counter_field(scenario_short: str, option_name: str) -> str:
    """
    Return a CSS attribute selector for the ``counter-field`` ``<input>`` inside
    the ``<app-phm-counter>`` component scoped to *scenario_short* / *option_name*.

    PHM names the counter host element::

        id="app-collector-{scenario_short}-cnt_coll_op_{option_name}"

    Example::

        _sel_counter_field("MS_Cycling", "Delayed Start (seconds)")
        # → '[id="app-collector-MS_Cycling-cnt_coll_op_Delayed Start (seconds)"] input.counter-field'

    Known *scenario_short* values extracted from PHM DOM (as of 2026-03-05):

    * ``"Manual"``
    * ``"IdleScreenOn"``
    * ``"IdleScreenOff"``
    * ``"ModernStandby"``
    * ``"MS_Cycling"``  ← Modern Standby Cycling
    * ``"VideoPlayback"``
    * ``"VideoStream"``
    """
    host_id = f"app-collector-{scenario_short}-cnt_coll_op_{option_name}"
    return f'[id="{host_id}"] input.counter-field'


def _sel_preset_scenario_radio(name: str) -> str:
    """
    Build a CSS attribute selector for a Preset Scenario radio input.

    PHM uses the naming convention::

        input[type="radio"]  id="chk_coll_sc_<scenario_name>"
        div.form-check-label id="lbl_coll_sc_<scenario_name>"

    Because the scenario name contains spaces the ID must be matched with
    the attribute selector ``[id="..."]`` rather than the ``#id`` shorthand
    (CSS ``#`` syntax requires escaping spaces).

    Args:
        name: The exact scenario label text, e.g. ``"Modern Standby Cycling"``.

    Returns:
        A CSS attribute selector string targeting the radio input.
    """
    return f'[id="chk_coll_sc_{name}"]'


# Text values that indicate the test has finished (legacy status-label approach)
_COMPLETION_STATUSES = {'pass', 'fail', 'completed', 'done', 'error'}

# PHM status / banner label — confirmed from DOM (id="lbl_coll_statusMsg")
# After a run it shows:  [ MS_Cycle 1 of 1 ] Traces saved to C:\...
_SEL_STATUS_MSG = '[id="lbl_coll_statusMsg"]'

# PHM log panel — confirmed from DOM (id="textArea_daq_logSummary")
_SEL_LOG_TEXTAREA = '[id="textArea_daq_logSummary"]'

# Sentinel line PHM writes to the log when a full collection cycle finishes
_LOG_COMPLETION_MARKER = 'Data analysis finished.'


class PHMUIMonitor:
    """
    Web UI monitor for PHM (Powerhouse Mountain).

    Controls PHM via Playwright by driving the web interface at
    ``http://<host>:<port>``.

    Example::

        monitor = PHMUIMonitor(host='localhost', port=1337)
        monitor.wait_for_ready(timeout=30)
        monitor.open_browser(headless=False)
        monitor.navigate_to_collector()
        monitor.set_cycle_count(10)
        monitor.start_test()
        monitor.wait_for_completion(timeout=3600)
        monitor.close_browser()
    """

    def __init__(
        self,
        host: str = 'localhost',
        port: int = 1337,
        headless: bool = False,
        browser_timeout: int = 30000,
    ):
        """
        Initialize PHM UI monitor.

        Args:
            host: PHM web server host (default ``'localhost'``).
            port: PHM web server port (default ``1337``).
            headless: Run browser in headless mode (default ``False``).
            browser_timeout: Playwright default timeout in milliseconds.

        Raises:
            PHMUIError: If playwright is not installed.
        """
        if not _PLAYWRIGHT_AVAILABLE:
            raise PHMUIError(
                "playwright is required for UI monitoring. "
                "Install it with: pip install playwright && playwright install chromium"
            )

        self.host = host
        self.port = port
        self.headless = headless
        self.browser_timeout = browser_timeout
        self.base_url = f"http://{host}:{port}"

        self._playwright = None
        self._browser = None
        self._context = None
        self._page = None
        self._connected = False

    # ------------------------------------------------------------------
    # Server readiness
    # ------------------------------------------------------------------

    def wait_for_ready(self, timeout: int = 30) -> bool:
        """
        Poll until the PHM web server is accepting TCP connections.

        Args:
            timeout: Total seconds to wait.

        Returns:
            True when the server is ready.

        Raises:
            PHMTimeoutError: If not ready within *timeout* seconds.
        """
        deadline = time.time() + timeout
        logger.info(f"Waiting for PHM server at {self.base_url} ...")
        while time.time() < deadline:
            try:
                with socket.create_connection((self.host, self.port), timeout=1):
                    logger.info("PHM server is ready")
                    return True
            except OSError:
                time.sleep(1)

        raise PHMTimeoutError(
            f"PHM server {self.base_url} did not become ready within {timeout}s"
        )

    # ------------------------------------------------------------------
    # Browser lifecycle
    # ------------------------------------------------------------------

    def open_browser(self, headless: Optional[bool] = None) -> None:
        """
        Launch a Playwright Chromium browser and open the PHM web UI.

        Args:
            headless: Override instance headless setting for this call.

        Raises:
            PHMUIError: If browser launch or page load fails.
        """
        if headless is None:
            headless = self.headless

        logger.info(f"Opening Playwright browser (headless={headless})")
        try:
            self._playwright = sync_playwright().start()
            self._browser = self._playwright.chromium.launch(headless=headless)
            self._context = self._browser.new_context()
            self._page = self._context.new_page()
            self._page.set_default_timeout(self.browser_timeout)
            self._page.goto(self.base_url)
            self._page.wait_for_load_state('networkidle')
            self._connected = True
            logger.info(f"Browser opened at {self.base_url}")
        except Exception as exc:
            raise PHMUIError(f"Failed to open browser: {exc}") from exc

    def close_browser(self) -> None:
        """Close the browser and stop Playwright."""
        logger.info("Closing Playwright browser")
        try:
            if self._page:
                self._page.close()
            if self._context:
                self._context.close()
            if self._browser:
                self._browser.close()
            if self._playwright:
                self._playwright.stop()
        except Exception:
            pass
        finally:
            self._page = None
            self._context = None
            self._browser = None
            self._playwright = None
            self._connected = False

    def _require_connected(self) -> None:
        """Raise PHMUIError if browser is not open."""
        if not self._connected or self._page is None:
            raise PHMUIError(
                "Browser not connected. Call open_browser() first."
            )

    # ------------------------------------------------------------------
    # Navigation
    # ------------------------------------------------------------------

    def navigate_to_collector(self) -> None:
        """
        Click the Collector tab in the PHM navigation.

        Raises:
            PHMUIError: If the Collector tab is not found.
        """
        self._require_connected()
        logger.info("Navigating to Collector tab")
        try:
            self._page.click(_SEL_COLLECTOR_TAB)
            self._page.wait_for_load_state('networkidle')
        except PlaywrightTimeoutError as exc:
            raise PHMUIError(
                f"Collector tab not found (selector: {_SEL_COLLECTOR_TAB!r}). "
                "Update _SEL_COLLECTOR_TAB with the real selector."
            ) from exc
        except Exception as exc:
            raise PHMUIError(f"Failed to navigate to Collector: {exc}") from exc

    def is_collection_options_expanded(self) -> bool:
        """
        Return True if the Collection Options panel is already expanded.

        Detection strategy (in order):

        1. ``aria-expanded="true"`` on the toggle element.
        2. The *Preset Scenarios* section is visible — this is the most
           reliable visual indicator because PHM always shows "Preset
           Scenarios" inside the panel when expanded.
        3. Falls back to ``False`` (treat as collapsed) on any error.
        """
        self._require_connected()
        try:
            # Strategy 1: aria-expanded attribute
            toggle = self._page.get_by_text("Collection Options", exact=False).first
            expanded_attr = toggle.get_attribute('aria-expanded', timeout=2000)
            if expanded_attr is not None:
                result = expanded_attr.lower() == 'true'
                logger.debug(f"aria-expanded={expanded_attr!r} → expanded={result}")
                return result
        except Exception:
            pass  # attribute absent or timeout → fall through

        try:
            # Strategy 2: Check if "Preset Scenarios" content is visible
            preset_section = self._page.get_by_text(
                "Preset Scenarios", exact=False
            ).first
            visible = preset_section.is_visible()
            logger.debug(f"'Preset Scenarios' visible={visible} → expanded={visible}")
            return visible
        except Exception:
            pass

        return False  # cannot determine → assume collapsed

    def expand_collection_options(self) -> None:
        """
        Ensure the *Collection Options* accordion is expanded.

        Checks the current state first via :meth:`is_collection_options_expanded`;
        skips the click if the panel is already open.

        Raises:
            PHMUIError: If the Collection Options toggle is not found.
        """
        self._require_connected()
        logger.info("Expanding Collection Options panel")
        try:
            # ── Check current state before clicking ──────────────────
            if self.is_collection_options_expanded():
                logger.info("Collection Options already expanded — skipping toggle")
                return

            # ── Not expanded → click the toggle ──────────────────────
            toggle = self._page.get_by_text(
                "Collection Options", exact=False
            ).first
            toggle.click()
            self._page.wait_for_timeout(400)  # brief pause for animation

            # ── Verify it opened ──────────────────────────────────────
            if self.is_collection_options_expanded():
                logger.info("Collection Options expanded")
            else:
                logger.warning(
                    "Clicked Collection Options toggle but panel may not have opened; "
                    "continuing anyway"
                )
        except PlaywrightTimeoutError as exc:
            raise PHMUIError(
                "Collection Options toggle not found. "
                "Verify the element text matches the real UI label."
            ) from exc
        except PHMUIError:
            raise
        except Exception as exc:
            raise PHMUIError(
                f"Failed to expand Collection Options: {exc}"
            ) from exc

    def select_preset_scenario(self, scenario_name: str) -> None:
        """
        Click the radio button for the named Preset Scenario and verify selection.

        Tries four strategies in order, stopping at the first that results in a
        *checked* radio button.  After each click the radio state is verified —
        this prevents false-positives where a text click hits a heading instead
        of the actual ``<input type="radio">``.

        Strategies:
            1. ``input[type="radio"]`` filtered by nearby text (most precise).
            2. ``label:has-text(name) input[type="radio"]`` — label wraps input.
            3. ``get_by_role("radio", name=name)`` — ARIA accessible name.
            4. ``get_by_label(name)`` — standard ``<label for=...>`` association.

        Args:
            scenario_name: Exact UI label of the scenario, e.g.
                           ``"Modern Standby Cycling"``.

        Raises:
            PHMUIError: If all strategies fail to select the radio button.
        """
        self._require_connected()
        logger.info(f"Selecting preset scenario: '{scenario_name}'")

        def _radio_locator():
            """Primary: radio input by PHM id convention chk_coll_sc_<name>."""
            return self._page.locator(f'[id="chk_coll_sc_{scenario_name}"]')

        def _is_radio_checked(locator) -> bool:
            """Return True if the located element is a checked radio input."""
            try:
                return locator.is_checked(timeout=2000)
            except Exception:
                return False

        # Strategy 1: click the radio input directly (chk_coll_sc_<name>)
        # Strategy 2: click the label div (lbl_coll_sc_<name>) — triggers the radio
        # Strategy 3: get_by_role radio with accessible name
        # Strategy 4: label:has-text > input[radio]
        strategies = [
            (
                f'[id="chk_coll_sc_{scenario_name}"] (radio input)',
                lambda: self._page.locator(f'[id="chk_coll_sc_{scenario_name}"]'),
            ),
            (
                f'[id="lbl_coll_sc_{scenario_name}"] (label div click)',
                lambda: self._page.locator(f'[id="lbl_coll_sc_{scenario_name}"]'),
            ),
            (
                "get_by_role radio",
                lambda: self._page.get_by_role("radio", name=scenario_name).first,
            ),
            (
                "label:has-text > input[radio]",
                lambda: self._page.locator(
                    f'label:has-text("{scenario_name}") input[type="radio"]'
                ).first,
            ),
        ]

        last_exc: Exception = RuntimeError("No strategies were attempted")
        for desc, locator_fn in strategies:
            try:
                locator = locator_fn()
                # Already selected — nothing to do
                if _is_radio_checked(_radio_locator()):
                    logger.info(
                        f"Scenario '{scenario_name}' already selected"
                    )
                    return
                locator.click(timeout=5000)
                self._page.wait_for_timeout(300)
                # Verify the radio is now actually checked
                if _is_radio_checked(_radio_locator()):
                    logger.info(
                        f"Scenario '{scenario_name}' selected and verified "
                        f"via strategy: {desc}"
                    )
                    return
                logger.debug(
                    f"Strategy '{desc}': click succeeded but radio not checked "
                    "— trying next strategy"
                )
            except Exception as exc:
                logger.debug(
                    f"select_preset_scenario strategy '{desc}' failed: {exc}"
                )
                last_exc = exc

        raise PHMUIError(
            f"All strategies failed to select (and verify) preset scenario "
            f"'{scenario_name}'. "
            f"Last error: {last_exc}. "
            "Use browser DevTools to inspect the radio element and update the selector."
        ) from last_exc

    def _fill_counter_field(
        self,
        scenario_short: str,
        option_name: str,
        value: int,
        timeout: int = 10_000,
    ) -> None:
        """
        Robustly set a PHM ``<app-phm-counter>`` field value.

        Waits for the input to become visible and enabled (not disabled), triple-
        clicks to select existing text, fills with *value*, then dispatches
        ``input`` + ``change`` events so Angular's ngModel picks up the change.

        Args:
            scenario_short: PHM short-name for the scenario prefix, e.g. ``"MS_Cycling"``.
            option_name:    Display label of the option, e.g. ``"Delayed Start (seconds)"``.
            value:          Integer value to set.
            timeout:        Milliseconds to wait for the field to become visible.

        Raises:
            PHMUIError: If the counter field cannot be found or filled.
        """
        sel = _sel_counter_field(scenario_short, option_name)
        logger.debug(f"Filling counter field '{option_name}' → {value}  (selector: {sel!r})")
        try:
            loc = self._page.locator(sel)
            loc.wait_for(state="visible", timeout=timeout)
            loc.click(click_count=3)
            loc.fill(str(value))
            loc.dispatch_event("input")
            loc.dispatch_event("change")
            logger.debug(f"Counter field '{option_name}' successfully set to {value}")
        except Exception as exc:
            raise PHMUIError(
                f"Failed to set counter field '{option_name}' "
                f"(selector: {sel!r}): {exc}"
            ) from exc

    def set_delayed_start(self, seconds: int, scenario_short: str = "MS_Cycling") -> None:
        """
        Fill the *Delayed Start (seconds)* counter of the active scenario.

        Args:
            seconds:        Non-negative integer delay in seconds.
            scenario_short: PHM short-name prefix (default ``"MS_Cycling"``).  Pass the
                            correct value when calling for other scenarios.

        Raises:
            PHMUIError: If the Delayed Start counter is not found.
        """
        self._require_connected()
        logger.info(f"Setting Delayed Start to {seconds} seconds")
        self._fill_counter_field(scenario_short, "Delayed Start (seconds)", seconds)

    def set_scenario_duration(self, minutes: int, scenario_short: str = "MS_Cycling") -> None:
        """
        Fill the *Scenario Duration (minutes)* counter of the active scenario.

        Args:
            minutes:        Positive integer duration in minutes.
            scenario_short: PHM short-name prefix (default ``"MS_Cycling"``).  Pass the
                            correct value when calling for other scenarios.

        Raises:
            PHMUIError: If the Scenario Duration counter is not found.
        """
        self._require_connected()
        logger.info(f"Setting Scenario Duration to {minutes} minutes")
        self._fill_counter_field(scenario_short, "Scenario Duration (minutes)", minutes)

    # ------------------------------------------------------------------
    # Parameter configuration
    # ------------------------------------------------------------------

    def set_cycle_count(self, count: int, scenario_short: str = "MS_Cycling") -> None:
        """
        Set the *Cycle Count* counter of the active scenario.

        Args:
            count:          Positive integer cycle count.
            scenario_short: PHM short-name prefix (default ``"MS_Cycling"``).  Pass the
                            correct value when calling for other scenarios.

        Raises:
            PHMUIError: If the Cycle Count counter is not found.
        """
        self._require_connected()
        logger.info(f"Setting cycle count to {count}")
        self._fill_counter_field(scenario_short, "Cycle Count", count)

    def set_test_duration(self, minutes: int) -> None:
        """
        Set the test duration in the PHM web UI.

        Args:
            minutes: Test duration in minutes.

        Raises:
            PHMUIError: If the duration input is not found.
        """
        self._require_connected()
        logger.info(f"Setting test duration to {minutes} minutes")
        try:
            self._page.fill(_SEL_DURATION_INPUT, str(minutes))
        except Exception as exc:
            raise PHMUIError(
                f"Failed to set duration (selector: {_SEL_DURATION_INPUT!r}): {exc}"
            ) from exc

    def set_modern_standby_mode(self, enabled: bool) -> None:
        """
        Enable or disable the Modern Standby (S0ix) checkbox.

        Args:
            enabled: True to enable, False to disable.

        Raises:
            PHMUIError: If the checkbox is not found.
        """
        self._require_connected()
        logger.info(f"Setting Modern Standby mode: {enabled}")
        try:
            checkbox = self._page.locator(_SEL_MODERN_STANDBY)
            is_checked = checkbox.is_checked()
            if is_checked != enabled:
                checkbox.click()
        except Exception as exc:
            raise PHMUIError(
                f"Failed to set Modern Standby (selector: {_SEL_MODERN_STANDBY!r}): {exc}"
            ) from exc

    # ------------------------------------------------------------------
    # Test control
    # ------------------------------------------------------------------

    def start_test(self) -> None:
        """
        Click the Start button to begin the PHM test.

        Raises:
            PHMUIError: If the Start button is not found.
        """
        self._require_connected()
        logger.info("Clicking Start button")
        try:
            self._page.click(_SEL_START_BTN)
        except Exception as exc:
            raise PHMUIError(
                f"Failed to click Start button (selector: {_SEL_START_BTN!r}): {exc}"
            ) from exc

    def stop_test(self) -> None:
        """
        Click the Stop button to halt the running test.

        Raises:
            PHMUIError: If the Stop button is not found.
        """
        self._require_connected()
        logger.info("Clicking Stop button")
        try:
            self._page.click(_SEL_STOP_BTN)
        except Exception as exc:
            raise PHMUIError(
                f"Failed to click Stop button (selector: {_SEL_STOP_BTN!r}): {exc}"
            ) from exc

    def wait_for_completion(self, timeout: int = 3600, poll_interval: int = 5) -> bool:
        """
        Poll the PHM *Show Log* panel until ``"Data analysis finished."`` appears.

        PHM appends log lines to the ``#textArea_daq_logSummary`` textarea while
        the collection is running.  The last line written after a successful
        cycle is ``"Data analysis finished."``.  This method waits for that
        sentinel to appear.

        Args:
            timeout:       Maximum seconds to wait before raising.
            poll_interval: Seconds between each log-text check (default 5).

        Returns:
            ``True`` when the completion marker is detected in the log.

        Raises:
            PHMTimeoutError: If the marker does not appear within *timeout* s.
        """
        self._require_connected()
        logger.info(
            f"Waiting for PHM log marker {_LOG_COMPLETION_MARKER!r} "
            f"(timeout={timeout}s, poll={poll_interval}s)"
        )
        deadline = time.time() + timeout
        last_line_count = 0
        while time.time() < deadline:
            log_text = self.get_log_text()
            lines = [l.strip() for l in log_text.splitlines() if l.strip()]
            # print new lines since last poll
            if len(lines) > last_line_count:
                for line in lines[last_line_count:]:
                    logger.info(f"[PHM Log] {line}")
                last_line_count = len(lines)
            if _LOG_COMPLETION_MARKER in log_text:
                logger.info("PHM log: 'Data analysis finished.' detected — collection complete")
                return True
            time.sleep(poll_interval)

        raise PHMTimeoutError(
            f"PHM test did not complete within {timeout} seconds "
            f"(marker {_LOG_COMPLETION_MARKER!r} not seen in log)"
        )

    def get_log_text(self) -> str:
        """
        Return the current contents of the PHM *Show Log* textarea.

        The textarea (``#textArea_daq_logSummary``) is populated by PHM while
        a collection is running.  Each line is a timestamped status message.

        Returns:
            The full log text as a string (may be empty if nothing has run yet).

        Raises:
            PHMUIError: If the log textarea element is not found.
        """
        self._require_connected()
        try:
            loc = self._page.locator(_SEL_LOG_TEXTAREA)
            loc.wait_for(state="attached", timeout=5_000)
            return loc.input_value()
        except Exception as exc:
            raise PHMUIError(
                f"Failed to read log textarea (selector: {_SEL_LOG_TEXTAREA!r}): {exc}"
            ) from exc

    # ------------------------------------------------------------------
    # Status & screenshot
    # ------------------------------------------------------------------

    def get_current_status(self) -> str:
        """
        Read the current status text from the PHM status label.

        Returns:
            Status string as shown in the UI (e.g. ``"Running"``, ``"Pass"``).

        Raises:
            PHMUIError: If the status element is not found.
        """
        self._require_connected()
        try:
            elem = self._page.locator(_SEL_STATUS_LABEL).first
            return elem.inner_text().strip()
        except Exception as exc:
            raise PHMUIError(
                f"Failed to read status (selector: {_SEL_STATUS_LABEL!r}): {exc}"
            ) from exc

    def get_traces_path(self) -> str:
        """
        Read the trace output directory from the PHM status banner.

        After a collection cycle completes, PHM updates the banner label
        (``#lbl_coll_statusMsg``) to something like::

            [ MS_Cycle 1 of 1 ] Traces saved to C:\\Program Files\\PowerhouseMountain\\traces\\Scenario2026-03-05-13-56-16

        This method extracts the path that follows ``"Traces saved to "``.

        Returns:
            Absolute path string of the trace folder.

        Raises:
            PHMUIError: If the status label is missing or does not contain the
                expected ``"Traces saved to"`` text.
        """
        self._require_connected()
        try:
            loc = self._page.locator(_SEL_STATUS_MSG)
            loc.wait_for(state="visible", timeout=10_000)
            full_text = loc.inner_text().strip()
        except Exception as exc:
            raise PHMUIError(
                f"Failed to read status banner (selector: {_SEL_STATUS_MSG!r}): {exc}"
            ) from exc

        marker = "Traces saved to "
        idx = full_text.find(marker)
        if idx == -1:
            raise PHMUIError(
                f"Status banner does not contain 'Traces saved to'. "
                f"Actual text: {full_text!r}"
            )
        traces_path = full_text[idx + len(marker):].strip()
        logger.info(f"Traces path: {traces_path}")
        return traces_path

    def take_screenshot(self, path: str) -> str:
        """
        Capture the full page as a PNG screenshot.

        Args:
            path: File path to write the PNG image.

        Returns:
            The resolved file path.

        Raises:
            PHMUIError: If screenshot capture fails.
        """
        self._require_connected()
        resolved = str(Path(path).resolve())
        os.makedirs(os.path.dirname(resolved), exist_ok=True)
        try:
            self._page.screenshot(path=resolved, full_page=True)
            logger.info(f"Screenshot saved: {resolved}")
            return resolved
        except Exception as exc:
            raise PHMUIError(f"Failed to take screenshot: {exc}") from exc

    # ------------------------------------------------------------------
    # Debug helpers
    # ------------------------------------------------------------------

    def dump_html(self, output_path: Optional[str] = None) -> str:
        """
        Return (and optionally save) the full outer HTML of the current page.

        Use this when a selector fails and you need to inspect the real DOM
        structure to write the correct locator.

        Args:
            output_path: If provided, write HTML to this file path.

        Returns:
            The full page HTML as a string.
        """
        self._require_connected()
        html = self._page.content()
        if output_path:
            resolved = str(Path(output_path).resolve())
            os.makedirs(os.path.dirname(resolved) or '.', exist_ok=True)
            Path(resolved).write_text(html, encoding='utf-8')
            logger.info(f"Page HTML saved to: {resolved}")
            print(f"  [debug] HTML saved → {resolved}")
        return html

    def dump_radio_candidates(self, keyword: str = "") -> list:
        """
        Print all clickable / interactive elements whose visible text contains
        *keyword* (case-insensitive).  Also separately lists every
        ``input[type=radio]`` on the page.

        Useful for diagnosing why ``select_preset_scenario`` cannot find an
        element — run this after navigation and read the printed tag/text/class
        to derive the correct selector.

        Args:
            keyword: Filter string; empty string returns all results.

        Returns:
            List of dicts with keys ``tag``, ``type``, ``text``, ``class``,
            ``id``, ``aria_label``, ``checked``.
        """
        self._require_connected()
        print("\n[debug] ── All input[type=radio] on page ─────────────────")
        radios = self._page.locator('input[type="radio"]').all()
        radio_info = []
        for i, r in enumerate(radios):
            try:
                info = {
                    'index':      i,
                    'id':         r.get_attribute('id') or '',
                    'name':       r.get_attribute('name') or '',
                    'value':      r.get_attribute('value') or '',
                    'aria_label': r.get_attribute('aria-label') or '',
                    'checked':    r.is_checked(),
                    'visible':    r.is_visible(),
                    # text of the parent element (often the label)
                    'parent_text': r.locator('..').inner_text().strip()[:80],
                }
                radio_info.append(info)
                print(f"  radio[{i}] id={info['id']!r:20s} "
                      f"name={info['name']!r:20s} "
                      f"value={info['value']!r:25s} "
                      f"checked={info['checked']} "
                      f"visible={info['visible']} "
                      f"parent_text={info['parent_text']!r}")
            except Exception as exc:
                print(f"  radio[{i}] <error reading attributes: {exc}>")

        kw_lower = keyword.lower()
        print(f"\n[debug] ── Elements with text containing {keyword!r} ───────")
        candidates = self._page.locator(
            'button, label, [role="radio"], [role="option"], '
            'span, div, li'
        ).all()
        matches = []
        for elem in candidates:
            try:
                text = elem.inner_text().strip()
                if kw_lower and kw_lower not in text.lower():
                    continue
                if not text:
                    continue
                info = {
                    'tag':        self._page.evaluate(
                                      '(e) => e.tagName', elem.element_handle()
                                  ).lower(),
                    'text':       text[:80],
                    'class':      elem.get_attribute('class') or '',
                    'id':         elem.get_attribute('id') or '',
                    'role':       elem.get_attribute('role') or '',
                    'aria_label': elem.get_attribute('aria-label') or '',
                }
                matches.append(info)
                print(f"  <{info['tag']}> "
                      f"id={info['id']!r:20s} "
                      f"role={info['role']!r:10s} "
                      f"class={info['class'][:30]!r:32s} "
                      f"text={info['text']!r}")
            except Exception:
                pass
        print("[debug] ─────────────────────────────────────────────────\n")
        return radio_info

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def is_connected(self) -> bool:
        """True if the browser is open and connected."""
        return self._connected

    @property
    def page(self):
        """The active Playwright Page, or None if not connected."""
        return self._page

